/* Part 2 Tweaker and Part 3 Writer: the milestones added for the 96 milestone course */
window.OPEBank.push(

{id: 'tweak-style', skill: 'tweak-style', kind: 'check', title: 'A green button',
 ask: 'CSS is the file that says how a page looks. In style.css, the .button rule is blue with dark text. Make its background #22C55E, a green, and its text white. Leave the padding, the corners and the body rule as they are.',
 files: {'style.css': "body {\n  font-family: Georgia, serif;\n  color: #1F2937;\n}\n\n.button {\n  background: #3B82F6;\n  color: #111827;\n  padding: 12px 20px;\n  border-radius: 8px;\n}\n"},
 test: "const css = fs.readFileSync(path.join(here, 'style.css'), 'utf8');\nconst m = css.match(/\\.button\\s*\\{([^}]*)\\}/);\ncheck('the .button rule is still there', () => assert.ok(m, 'there is no .button { } rule any more'));\nconst rule = m ? m[1] : '';\ncheck('the background is #22C55E', () => assert.ok(/background(-color)?\\s*:\\s*#22C55E\\s*(;|$)/i.test(rule), 'the .button background is not #22C55E'));\ncheck('the text is white', () => assert.ok(/(^|[;\\s])color\\s*:\\s*(white|#fff|#ffffff)\\s*(;|$)/i.test(rule), 'the .button text colour is not white'));\ncheck('the padding and corners are the same', () => { assert.ok(/padding\\s*:\\s*12px 20px/.test(rule), 'the padding changed'); assert.ok(/border-radius\\s*:\\s*8px/.test(rule), 'the corners changed'); });\ncheck('the body rule is the same', () => assert.ok(/body\\s*\\{[^}]*Georgia, serif;[^}]*#1F2937;[^}]*\\}/.test(css), 'the body rule changed'));",
 solve: {'style.css': "body {\n  font-family: Georgia, serif;\n  color: #1F2937;\n}\n\n.button {\n  background: #22C55E;\n  color: white;\n  padding: 12px 20px;\n  border-radius: 8px;\n}\n"}},

{id: 'tweak-html', skill: 'tweak-html', kind: 'check', title: 'New heading and a Book now link',
 ask: 'HTML is the file that says what is on a page. In index.html, change the words in the h1, the big heading, to  Fresh cuts, booked in a minute.  Then add a link inside the header, after the h1:  <a href="/book">Book now</a>  Leave the rest of the page as it is.',
 files: {'index.html': "<!doctype html>\n<html>\n<head>\n  <title>Corner Cuts</title>\n  <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n<body>\n  <header>\n    <h1>Welcome</h1>\n  </header>\n  <main>\n    <p>Haircuts for everyone, six days a week.</p>\n  </main>\n</body>\n</html>\n"},
 test: "const html = fs.readFileSync(path.join(here, 'index.html'), 'utf8');\ncheck('the h1 says the new sentence', () => { const h = html.match(/<h1[^>]*>([\\s\\S]*?)<\\/h1>/); assert.ok(h, 'there is no h1'); assert.strictEqual(h[1].trim(), 'Fresh cuts, booked in a minute.'); });\ncheck('there is still only one h1', () => assert.strictEqual((html.match(/<h1/g) || []).length, 1));\ncheck('the Book now link is inside the header', () => { const h = html.match(/<header[^>]*>([\\s\\S]*?)<\\/header>/); assert.ok(h, 'there is no header'); assert.ok(/<a\\s+href=\"\\/book\"\\s*>\\s*Book now\\s*<\\/a>/.test(h[1]), 'no <a href=\"/book\">Book now</a> inside the header'); });\ncheck('the rest of the page is the same', () => { assert.ok(html.includes('<title>Corner Cuts</title>'), 'the title changed'); assert.ok(html.includes('<p>Haircuts for everyone, six days a week.</p>'), 'the paragraph changed'); assert.ok(html.includes('href=\"style.css\"'), 'the stylesheet link changed'); });",
 solve: {'index.html': "<!doctype html>\n<html>\n<head>\n  <title>Corner Cuts</title>\n  <link rel=\"stylesheet\" href=\"style.css\">\n</head>\n<body>\n  <header>\n    <h1>Fresh cuts, booked in a minute.</h1>\n    <a href=\"/book\">Book now</a>\n  </header>\n  <main>\n    <p>Haircuts for everyone, six days a week.</p>\n  </main>\n</body>\n</html>\n"}},

{id: 'tweak-config', skill: 'tweak-config', kind: 'check', title: 'Dark mode and euros',
 ask: 'settings.json is a settings file. JSON is a way of writing data as "key": value pairs. Turn "darkMode" to true and set "currency" to "EUR". Leave every other key exactly as it is, and keep the file valid JSON: quotes around the keys and the text, commas between pairs, no comma after the last one.',
 files: {'settings.json': "{\n  \"shopName\": \"Corner Cuts\",\n  \"darkMode\": false,\n  \"currency\": \"USD\",\n  \"openHours\": {\n    \"from\": 9,\n    \"to\": 17\n  },\n  \"languages\": [\n    \"en\",\n    \"am\"\n  ]\n}\n"},
 test: "let s;\ncheck('settings.json is still valid JSON', () => { s = JSON.parse(fs.readFileSync(path.join(here, 'settings.json'), 'utf8')); });\nif (s) {\n  check('darkMode is true', () => assert.strictEqual(s.darkMode, true));\n  check('currency is EUR', () => assert.strictEqual(s.currency, 'EUR'));\n  check('the other keys are the same', () => { assert.strictEqual(s.shopName, 'Corner Cuts'); assert.deepStrictEqual(s.openHours, { from: 9, to: 17 }); assert.deepStrictEqual(s.languages, ['en', 'am']); assert.strictEqual(Object.keys(s).length, 5, 'a key was added or taken out'); });\n}",
 solve: {'settings.json': "{\n  \"shopName\": \"Corner Cuts\",\n  \"darkMode\": true,\n  \"currency\": \"EUR\",\n  \"openHours\": {\n    \"from\": 9,\n    \"to\": 17\n  },\n  \"languages\": [\n    \"en\",\n    \"am\"\n  ]\n}\n"}},

{id: 'tweak-field', skill: 'tweak-field', kind: 'check', title: 'Rename nm to name',
 ask: 'A field is one named part of an object, like the age in { age: 36 }. In solution.cjs a person\'s name is kept in a field called nm, which is hard to read. Rename it to name everywhere it is used, so that nm is gone from the file and all three functions still work. Your editor can find every place for you: search the file for nm.',
 files: {'solution.cjs': "function makePerson(nm, age) {\n  return { nm: nm, age: age };\n}\n\nfunction describe(person) {\n  return person.nm + ' is ' + person.age;\n}\n\nfunction byName(people) {\n  return people.slice().sort((a, b) => a.nm.localeCompare(b.nm));\n}\n\nmodule.exports = { makePerson, describe, byName };\n"},
 test: "const src = fs.readFileSync(path.join(here, 'solution.cjs'), 'utf8');\nconst p = load('solution.cjs');\ncheck('makePerson gives a name field', () => assert.deepStrictEqual(p.makePerson('Ada', 36), { name: 'Ada', age: 36 }));\ncheck('describe reads the name field', () => assert.strictEqual(p.describe({ name: 'Ada', age: 36 }), 'Ada is 36'));\ncheck('byName sorts by the name field', () => assert.deepStrictEqual(p.byName([{ name: 'Sam', age: 1 }, { name: 'Ada', age: 2 }]).map(x => x.name), ['Ada', 'Sam']));\ncheck('nm is gone from the file', () => assert.ok(!/\\bnm\\b/.test(src), 'nm is still in solution.cjs'));",
 solve: {'solution.cjs': "function makePerson(name, age) {\n  return { name: name, age: age };\n}\n\nfunction describe(person) {\n  return person.name + ' is ' + person.age;\n}\n\nfunction byName(people) {\n  return people.slice().sort((a, b) => a.name.localeCompare(b.name));\n}\n\nmodule.exports = { makePerson, describe, byName };\n"}},

{id: 'tweak-default', skill: 'tweak-default', kind: 'check', title: 'Hello, friend',
 ask: 'greet in solution.cjs says "Hello, undefined!" when it is called with no name. undefined is what JavaScript gives a value that was never set. Give greet a default so that with no name it says "Hello, friend!". With a name it must still say "Hello, Ada!".',
 files: {'solution.cjs': "function greet(name) {\n  return 'Hello, ' + name + '!';\n}\n\nmodule.exports = { greet };\n"},
 test: "const { greet } = load('solution.cjs');\ncheck('no name says Hello, friend!', () => assert.strictEqual(greet(), 'Hello, friend!'));\ncheck('Ada still says Hello, Ada!', () => assert.strictEqual(greet('Ada'), 'Hello, Ada!'));",
 solve: {'solution.cjs': "function greet(name = 'friend') {\n  return 'Hello, ' + name + '!';\n}\n\nmodule.exports = { greet };\n"}},

{id: 'tweak-order', skill: 'tweak-order', kind: 'check', title: 'Most expensive first',
 ask: 'sortByPrice in solution.cjs puts the cheapest thing first. The shop wants the most expensive thing first now. Change the order. It must still leave the list it was given as it was, which is what .slice() is there for: it makes a copy to sort.',
 files: {'solution.cjs': "function sortByPrice(items) {\n  return items.slice().sort((a, b) => a.price - b.price);\n}\n\nmodule.exports = { sortByPrice };\n"},
 test: "const { sortByPrice } = load('solution.cjs');\nconst items = [{ name: 'Tea', price: 2 }, { name: 'Cake', price: 5 }, { name: 'Coffee', price: 3 }];\ncheck('most expensive first', () => assert.deepStrictEqual(sortByPrice(items).map(i => i.name), ['Cake', 'Coffee', 'Tea']));\ncheck('the list it was given is not changed', () => assert.deepStrictEqual(items.map(i => i.name), ['Tea', 'Cake', 'Coffee']));\ncheck('all the things are still there', () => assert.strictEqual(sortByPrice(items).length, 3));",
 solve: {'solution.cjs': "function sortByPrice(items) {\n  return items.slice().sort((a, b) => b.price - a.price);\n}\n\nmodule.exports = { sortByPrice };\n"}},

{id: 'tweak-remove', skill: 'tweak-remove', kind: 'check', title: 'Take the discount out',
 ask: 'The shop has stopped giving 10% off. Take the discount out of solution.cjs completely: the DISCOUNT value, the discount function, its use inside total, and its name in module.exports. total must then give the full price. When you are done the word discount should not be in the file at all.',
 files: {'solution.cjs': "const DISCOUNT = 0.1;\n\nfunction discount(amount) {\n  return amount * DISCOUNT;\n}\n\nfunction subtotal(items) {\n  return items.reduce((sum, i) => sum + i.price * i.qty, 0);\n}\n\nfunction total(items) {\n  const sub = subtotal(items);\n  return sub - discount(sub);\n}\n\nmodule.exports = { subtotal, total, discount };\n"},
 test: "const src = fs.readFileSync(path.join(here, 'solution.cjs'), 'utf8');\nconst s = load('solution.cjs');\nconst cart = [{ price: 10, qty: 2 }, { price: 5, qty: 1 }];\ncheck('total is the full price', () => assert.strictEqual(s.total(cart), 25));\ncheck('subtotal still works', () => assert.strictEqual(s.subtotal(cart), 25));\ncheck('an empty cart is 0', () => assert.strictEqual(s.total([]), 0));\ncheck('the word discount is gone', () => assert.ok(!/discount/i.test(src), 'discount is still in solution.cjs'));",
 solve: {'solution.cjs': "function subtotal(items) {\n  return items.reduce((sum, i) => sum + i.price * i.qty, 0);\n}\n\nfunction total(items) {\n  return subtotal(items);\n}\n\nmodule.exports = { subtotal, total };\n"}},

{id: 'write-strings', skill: 'write-strings', kind: 'check', title: 'Write formatName',
 ask: 'Write formatName(first, last) in solution.cjs. It gives back the last name, a comma and a space, then the first name, so formatName("Ada", "Lovelace") is "Lovelace, Ada". People often type extra spaces, so trim them first. To trim means to cut the spaces off the start and the end: "  Ada ".trim() is "Ada".',
 files: {'solution.cjs': "function formatName(first, last) {\n  // your code here\n}\n\nmodule.exports = { formatName };\n"},
 test: "const { formatName } = load('solution.cjs');\ncheck('Lovelace, Ada', () => assert.strictEqual(formatName('Ada', 'Lovelace'), 'Lovelace, Ada'));\ncheck('another name', () => assert.strictEqual(formatName('Grace', 'Hopper'), 'Hopper, Grace'));\ncheck('extra spaces are trimmed', () => assert.strictEqual(formatName('  Ada ', ' Lovelace  '), 'Lovelace, Ada'));",
 solve: {'solution.cjs': "function formatName(first, last) {\n  return last.trim() + ', ' + first.trim();\n}\n\nmodule.exports = { formatName };\n"}},

{id: 'write-math', skill: 'write-math', kind: 'check', title: 'Write splitBill',
 ask: 'Money is safest in cents, whole numbers, because 0.1 + 0.2 is not exactly 0.3 in JavaScript. Write splitBill(totalCents, people) in solution.cjs. It gives back a list with one amount in cents for each person, and the amounts must add up to the total exactly. When it does not divide evenly, the first people pay one extra cent each. So splitBill(1000, 3) is [334, 333, 333]. Math.floor rounds down and % gives the remainder.',
 files: {'solution.cjs': "function splitBill(totalCents, people) {\n  // your code here\n}\n\nmodule.exports = { splitBill };\n"},
 test: "const { splitBill } = load('solution.cjs');\nconst sum = a => a.reduce((s, x) => s + x, 0);\ncheck('1000 for 3 is 334, 333, 333', () => assert.deepStrictEqual(splitBill(1000, 3), [334, 333, 333]));\ncheck('1000 for 4 is even', () => assert.deepStrictEqual(splitBill(1000, 4), [250, 250, 250, 250]));\ncheck('5 for 3 is 2, 2, 1', () => assert.deepStrictEqual(splitBill(5, 3), [2, 2, 1]));\ncheck('one person pays it all', () => assert.deepStrictEqual(splitBill(4599, 1), [4599]));\ncheck('always adds back to the total, in whole cents', () => { for (const [t, p] of [[10001, 7], [99, 10], [12345, 6], [0, 3]]) { const r = splitBill(t, p); assert.strictEqual(r.length, p); assert.strictEqual(sum(r), t, t + ' for ' + p + ' adds up to ' + sum(r)); assert.ok(r.every(Number.isInteger), 'not whole cents: ' + r); } });",
 solve: {'solution.cjs': "function splitBill(totalCents, people) {\n  const each = Math.floor(totalCents / people);\n  const extra = totalCents % people;\n  const out = [];\n  for (let i = 0; i < people; i++) {\n    out.push(i < extra ? each + 1 : each);\n  }\n  return out;\n}\n\nmodule.exports = { splitBill };\n"}},

{id: 'write-objects', skill: 'write-objects', kind: 'check', title: 'Write makeBooking',
 ask: 'Write makeBooking(name, service, price) in solution.cjs. It gives back an object with five fields: name, service and price as they were given, status set to "held", and createdAt set to the time right now, which is new Date().',
 files: {'solution.cjs': "function makeBooking(name, service, price) {\n  // your code here\n}\n\nmodule.exports = { makeBooking };\n"},
 test: "const { makeBooking } = load('solution.cjs');\nconst before = Date.now();\nconst b = makeBooking('Ada', 'Haircut', 30);\ncheck('it gives back an object', () => assert.ok(b && typeof b === 'object', 'makeBooking gave back ' + b));\nif (b && typeof b === 'object') {\n  check('name, service and price', () => { assert.strictEqual(b.name, 'Ada'); assert.strictEqual(b.service, 'Haircut'); assert.strictEqual(b.price, 30); });\n  check('status is held', () => assert.strictEqual(b.status, 'held'));\n  check('createdAt is a Date from right now', () => { assert.ok(b.createdAt instanceof Date, 'createdAt is not a Date'); assert.ok(Math.abs(b.createdAt.getTime() - before) < 5000, 'createdAt is not the time now'); });\n  check('five fields, no more', () => assert.deepStrictEqual(Object.keys(b).sort(), ['createdAt', 'name', 'price', 'service', 'status']));\n  check('each call makes a new object', () => assert.notStrictEqual(makeBooking('Sam', 'Shave', 15), b));\n}",
 solve: {'solution.cjs': "function makeBooking(name, service, price) {\n  return { name, service, price, status: 'held', createdAt: new Date() };\n}\n\nmodule.exports = { makeBooking };\n"}},

{id: 'write-map-filter', skill: 'write-map-filter', kind: 'check', title: 'Write paidOver20',
 ask: 'Write paidOver20(orders) in solution.cjs. Each order looks like { id: 7, total: 25, paid: true }. Give back the ids of the orders that are paid and whose total is over $20, in the same order. Use .filter to keep only the orders you want, then .map to turn each order into its id. Exactly $20 is not over $20.',
 files: {'solution.cjs': "function paidOver20(orders) {\n  // your code here\n}\n\nmodule.exports = { paidOver20 };\n"},
 test: "const src = fs.readFileSync(path.join(here, 'solution.cjs'), 'utf8');\nconst { paidOver20 } = load('solution.cjs');\nconst orders = [{ id: 1, total: 25, paid: true }, { id: 2, total: 50, paid: false }, { id: 3, total: 20, paid: true }, { id: 4, total: 20.5, paid: true }, { id: 5, total: 5, paid: true }];\ncheck('the paid orders over $20', () => assert.deepStrictEqual(paidOver20(orders), [1, 4]));\ncheck('no orders gives an empty list', () => assert.deepStrictEqual(paidOver20([]), []));\ncheck('it uses .map( and .filter(', () => { assert.ok(src.includes('.filter('), 'there is no .filter( in solution.cjs'); assert.ok(src.includes('.map('), 'there is no .map( in solution.cjs'); });",
 solve: {'solution.cjs': "function paidOver20(orders) {\n  return orders.filter(o => o.paid && o.total > 20).map(o => o.id);\n}\n\nmodule.exports = { paidOver20 };\n"}},

{id: 'write-find', skill: 'write-find', kind: 'check', title: 'Write findUser, allAdults and anyAdmin',
 ask: 'Write three functions in solution.cjs. Each user looks like { email: "ada@x.com", age: 36, role: "admin" }.\n  findUser(users, email) gives back the user with that email, or null if there is none.\n  allAdults(users) gives true if every user is 18 or older.\n  anyAdmin(users) gives true if at least one user has the role "admin".\nLists have .find, .every and .some for exactly these jobs.',
 files: {'solution.cjs': "function findUser(users, email) {\n  // your code here\n}\n\nfunction allAdults(users) {\n  // your code here\n}\n\nfunction anyAdmin(users) {\n  // your code here\n}\n\nmodule.exports = { findUser, allAdults, anyAdmin };\n"},
 test: "const s = load('solution.cjs');\nconst ada = { email: 'ada@x.com', age: 36, role: 'admin' };\nconst sam = { email: 'sam@x.com', age: 17, role: 'member' };\nconst lee = { email: 'lee@x.com', age: 22, role: 'member' };\ncheck('findUser finds the user', () => assert.strictEqual(s.findUser([ada, sam, lee], 'sam@x.com'), sam));\ncheck('findUser gives null when there is none', () => assert.strictEqual(s.findUser([ada, sam], 'nobody@x.com'), null));\ncheck('allAdults is false with a 17 year old', () => assert.strictEqual(s.allAdults([ada, sam, lee]), false));\ncheck('allAdults is true when all are 18 or more', () => { assert.strictEqual(s.allAdults([ada, lee]), true); assert.strictEqual(s.allAdults([{ age: 18 }]), true); });\ncheck('anyAdmin is true with one admin', () => assert.strictEqual(s.anyAdmin([sam, ada]), true));\ncheck('anyAdmin is false with none', () => { assert.strictEqual(s.anyAdmin([sam, lee]), false); assert.strictEqual(s.anyAdmin([]), false); });",
 solve: {'solution.cjs': "function findUser(users, email) {\n  return users.find(u => u.email === email) || null;\n}\n\nfunction allAdults(users) {\n  return users.every(u => u.age >= 18);\n}\n\nfunction anyAdmin(users) {\n  return users.some(u => u.role === 'admin');\n}\n\nmodule.exports = { findUser, allAdults, anyAdmin };\n"}},

{id: 'write-dates', skill: 'write-dates', kind: 'check', title: 'Write daysBetween',
 ask: 'Write daysBetween(a, b) in solution.cjs. a and b are dates written like "2026-09-01". It gives back how many whole days are between them, so daysBetween("2026-09-01", "2026-09-18") is 17, and it is the same whichever date comes first. Work in UTC, the world clock that never moves for summer time, or a day with a clock change will come out as 23 or 25 hours. Date.UTC(year, month - 1, day) gives the time in milliseconds, and a day is 86400000 of them.',
 files: {'solution.cjs': "function daysBetween(a, b) {\n  // your code here\n}\n\nmodule.exports = { daysBetween };\n"},
 test: "const { daysBetween } = load('solution.cjs');\ncheck('1 to 18 September is 17', () => assert.strictEqual(daysBetween('2026-09-01', '2026-09-18'), 17));\ncheck('the other way round is also 17', () => assert.strictEqual(daysBetween('2026-09-18', '2026-09-01'), 17));\ncheck('the same day is 0', () => assert.strictEqual(daysBetween('2026-09-18', '2026-09-18'), 0));\ncheck('across the spring clock change', () => assert.strictEqual(daysBetween('2026-03-01', '2026-04-01'), 31));\ncheck('across the autumn clock change', () => assert.strictEqual(daysBetween('2026-10-20', '2026-11-10'), 21));\ncheck('a leap year', () => assert.strictEqual(daysBetween('2028-02-28', '2028-03-01'), 2));\ncheck('across a new year', () => assert.strictEqual(daysBetween('2026-12-25', '2027-01-01'), 7));",
 solve: {'solution.cjs': "function toDay(text) {\n  const [y, m, d] = text.split('-').map(Number);\n  return Date.UTC(y, m - 1, d);\n}\n\nfunction daysBetween(a, b) {\n  return Math.round(Math.abs(toDay(b) - toDay(a)) / 86400000);\n}\n\nmodule.exports = { daysBetween };\n"}},

{id: 'write-validation', skill: 'write-validation', kind: 'check', title: 'Write isEmail and isPhone',
 ask: 'Write two checks in solution.cjs that give true or false.\n  isEmail(text): some letters, one @, more letters, a dot and more letters, with no spaces. So "ada@example.com" is true and "ada@example" is false.\n  isPhone(text): 10 to 15 digits. Spaces and dashes between them are allowed, and one + at the very start. So "+251 911 234 567" is true and "12345" is false.\nA regular expression, a pattern written between slashes like /^\\d+$/, is one way to do it. Another is to take out the spaces and dashes and count what is left.',
 files: {'solution.cjs': "function isEmail(text) {\n  // your code here\n}\n\nfunction isPhone(text) {\n  // your code here\n}\n\nmodule.exports = { isEmail, isPhone };\n"},
 test: "const { isEmail, isPhone } = load('solution.cjs');\nfor (const t of ['ada@example.com', 'sam.lee+shop@mail.co.uk', 'x@y.io']) check('email ok: ' + t, () => assert.strictEqual(isEmail(t), true));\nfor (const t of ['ada@', 'ada example.com', 'ada@example', '', '@example.com', 'ada@@example.com', 'ada @example.com']) check('email not ok: \"' + t + '\"', () => assert.strictEqual(isEmail(t), false));\nfor (const t of ['5551234567', '555 123 4567', '555-123-4567', '+251 911 234 567', '+44 20 7946 0958', '123456789012345']) check('phone ok: ' + t, () => assert.strictEqual(isPhone(t), true));\nfor (const t of ['12345', 'call me', '555-123-4567 ext 9', '1234567890123456', '++15551234567', '555+1234567890', '']) check('phone not ok: \"' + t + '\"', () => assert.strictEqual(isPhone(t), false));",
 solve: {'solution.cjs': "function isEmail(text) {\n  return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(text);\n}\n\nfunction isPhone(text) {\n  if (!/^\\+?[\\d\\s-]+$/.test(text)) return false;\n  const digits = text.replace(/\\D/g, '').length;\n  return digits >= 10 && digits <= 15;\n}\n\nmodule.exports = { isEmail, isPhone };\n"}}

);
