/* Part 4 Builder and Part 5 Debugger: the milestones added for the 96 milestone course */
window.OPEBank.push(
{id: "build-modules", skill: "build-modules", kind: 'check', title: "Two files that work together",
 ask: "Build this in two files, from blank, no AI. In money.cjs, write and export formatCents(cents): it gives back a price as text with a dollar sign and two decimals, so 1250 becomes \"$12.50\" and 5 becomes \"$0.05\". In cart.cjs, require ./money.cjs (require means load another file and use what it exports) and write and export cartLine(item). An item looks like { name: \"Tea\", qty: 2, cents: 250 }, where cents is the price of one. cartLine gives back \"Tea x2 $5.00\": the name, x and the quantity, then the price of all of them, made with formatCents.",
 files: {"money.cjs": "// formatCents goes here\n", "cart.cjs": "// cartLine goes here\n"},
 test: "const { formatCents } = load('money.cjs');\ncheck('formatCents(1250) is $12.50', () => assert.strictEqual(formatCents(1250), '$12.50'));\ncheck('formatCents(5) is $0.05', () => assert.strictEqual(formatCents(5), '$0.05'));\ncheck('formatCents(0) is $0.00', () => assert.strictEqual(formatCents(0), '$0.00'));\nconst { cartLine } = load('cart.cjs');\ncheck('Tea x2 $5.00', () => assert.strictEqual(cartLine({ name: 'Tea', qty: 2, cents: 250 }), 'Tea x2 $5.00'));\ncheck('Cake x1 $3.99', () => assert.strictEqual(cartLine({ name: 'Cake', qty: 1, cents: 399 }), 'Cake x1 $3.99'));\ncheck('cart.cjs requires money.cjs', () => {\n  const src = fs.readFileSync(path.join(here, 'cart.cjs'), 'utf8');\n  assert.ok(/require\\(\\s*['\"]\\.\\/money(\\.cjs)?['\"]\\s*\\)/.test(src), 'cart.cjs does not require ./money.cjs');\n});",
 solve: {"money.cjs": "function formatCents(cents) {\n  return '$' + (cents / 100).toFixed(2);\n}\n\nmodule.exports = { formatCents };\n", "cart.cjs": "const { formatCents } = require('./money.cjs');\n\nfunction cartLine(item) {\n  return item.name + ' x' + item.qty + ' ' + formatCents(item.qty * item.cents);\n}\n\nmodule.exports = { cartLine };\n"}},

{id: "build-cli", skill: "build-cli", kind: 'check', title: "A tip calculator you run",
 ask: "Build tip.cjs from blank, no AI. It is a program you run from the terminal: node tip.cjs 80 15 means a bill of 80 and a tip of 15 percent. It prints exactly \"Tip: $12.00, total: $92.00\". What was typed after the file name is in process.argv (a list: process.argv[2] is the first thing typed, process.argv[3] the second). If a number is missing or is not a number, it prints \"Usage: node tip.cjs <bill> <percent>\" and stops with exit code 1 (the code a program gives back when it ends; 0 means all good, anything else means it failed). Use process.exit(1).",
 files: {"tip.cjs": "// what was typed is in process.argv\n"},
 test: "const { spawnSync } = require('child_process');\nconst run = args => spawnSync(process.execPath, [path.join(here, 'tip.cjs')].concat(args), { cwd: here, encoding: 'utf8', timeout: 10000 });\ncheck('80 15 prints the tip and the total', () => {\n  const r = run(['80', '15']);\n  assert.strictEqual(r.stdout.trim(), 'Tip: $12.00, total: $92.00');\n  assert.strictEqual(r.status, 0, 'it should end with exit code 0');\n});\ncheck('50 20 prints the tip and the total', () => assert.strictEqual(run(['50', '20']).stdout.trim(), 'Tip: $10.00, total: $60.00'));\ncheck('nothing typed shows the usage and exit code 1', () => {\n  const r = run([]);\n  assert.ok((r.stdout + r.stderr).includes('Usage: node tip.cjs <bill> <percent>'), 'it did not print the usage line');\n  assert.strictEqual(r.status, 1, 'the exit code was ' + r.status);\n});\ncheck('a word instead of a number shows the usage and exit code 1', () => {\n  const r = run(['abc', '15']);\n  assert.ok((r.stdout + r.stderr).includes('Usage: node tip.cjs <bill> <percent>'), 'it did not print the usage line');\n  assert.strictEqual(r.status, 1, 'the exit code was ' + r.status);\n});",
 solve: {"tip.cjs": "const bill = Number(process.argv[2]);\nconst percent = Number(process.argv[3]);\n\nif (process.argv.length < 4 || Number.isNaN(bill) || Number.isNaN(percent)) {\n  console.log('Usage: node tip.cjs <bill> <percent>');\n  process.exit(1);\n}\n\nconst tip = bill * percent / 100;\nconsole.log('Tip: $' + tip.toFixed(2) + ', total: $' + (bill + tip).toFixed(2));\n"}},

{id: "build-json", skill: "build-json", kind: 'check', title: "Save a list, load it back",
 ask: "Build store.cjs from blank, no AI. Write and export save(file, list), which writes the list into the file as JSON (a way of writing data as text, made with JSON.stringify), and load(file), which reads it back with JSON.parse and gives back the list. If the file is not there, load gives back an empty list. If the file holds broken JSON, load also gives back an empty list instead of crashing.",
 files: {"store.cjs": "// save and load go here\n"},
 test: "const { save, load: loadList } = load('store.cjs');\nconst tmp = path.join(here, 'tmp-store.json');\ntry {\n  check('what you save comes back', () => {\n    save(tmp, [{ name: 'Tea', price: 3 }, 'two', 3]);\n    assert.deepStrictEqual(loadList(tmp), [{ name: 'Tea', price: 3 }, 'two', 3]);\n  });\n  check('the file holds JSON', () => {\n    save(tmp, [1, 2]);\n    assert.deepStrictEqual(JSON.parse(fs.readFileSync(tmp, 'utf8')), [1, 2]);\n  });\n  check('a missing file gives an empty list', () => {\n    try { fs.unlinkSync(tmp); } catch (e) {}\n    assert.deepStrictEqual(loadList(tmp), []);\n  });\n  check('broken JSON gives an empty list', () => {\n    fs.writeFileSync(tmp, '[{ broken');\n    assert.deepStrictEqual(loadList(tmp), []);\n  });\n} finally { try { fs.unlinkSync(tmp); } catch (e) {} }",
 solve: {"store.cjs": "const fs = require('fs');\n\nfunction save(file, list) {\n  fs.writeFileSync(file, JSON.stringify(list, null, 2));\n}\n\nfunction load(file) {\n  try {\n    return JSON.parse(fs.readFileSync(file, 'utf8'));\n  } catch (e) {\n    return [];\n  }\n}\n\nmodule.exports = { save, load };\n"}},

{id: "build-classes", skill: "build-classes", kind: 'check', title: "A basket that keeps its own things",
 ask: "Build a class called Basket in solution.cjs, no AI. A class is a plan for making objects that each keep their own data and have their own actions. new Basket() starts empty. add(name, price) puts one thing in. remove(name) takes out one thing with that name, and does nothing if there is none. total() gives back the sum of the prices. count() gives back how many things are in it. Two baskets never share their things.",
 files: {"solution.cjs": "class Basket {\n  // your code here\n}\n\nmodule.exports = { Basket };\n"},
 test: "const { Basket } = load('solution.cjs');\ncheck('a new basket is empty', () => { const b = new Basket(); assert.strictEqual(b.count(), 0); assert.strictEqual(b.total(), 0); });\ncheck('add, count and total', () => { const b = new Basket(); b.add('tea', 3); b.add('cake', 4.5); assert.strictEqual(b.count(), 2); assert.strictEqual(b.total(), 7.5); });\ncheck('remove takes out one', () => { const b = new Basket(); b.add('tea', 3); b.add('tea', 3); b.add('cake', 4); b.remove('tea'); assert.strictEqual(b.count(), 2); assert.strictEqual(b.total(), 7); });\ncheck('removing something not there does nothing', () => { const b = new Basket(); b.add('tea', 3); b.remove('milk'); assert.strictEqual(b.count(), 1); });\ncheck('two baskets are separate', () => { const a = new Basket(), b = new Basket(); a.add('tea', 3); assert.strictEqual(b.count(), 0); assert.strictEqual(a.count(), 1); });",
 solve: {"solution.cjs": "class Basket {\n  constructor() {\n    this.items = [];\n  }\n\n  add(name, price) {\n    this.items.push({ name, price });\n  }\n\n  remove(name) {\n    const i = this.items.findIndex(item => item.name === name);\n    if (i !== -1) this.items.splice(i, 1);\n  }\n\n  total() {\n    return this.items.reduce((sum, item) => sum + item.price, 0);\n  }\n\n  count() {\n    return this.items.length;\n  }\n}\n\nmodule.exports = { Basket };\n"}},

{id: "build-fetch", skill: "build-fetch", kind: 'check', title: "Ask for the weather",
 ask: "Write and export the async function getWeather(city, fetchFn) in solution.cjs, no AI. fetchFn works like fetch, the browser tool for asking another computer for data. It is passed in so the test can use a pretend one and no internet is needed. Call fetchFn with \"https://weather.example/api?city=\" and the city after it, made safe with encodeURIComponent(city). Await the response. If response.ok is false, throw new Error(\"Could not get the weather\"). Otherwise await response.json(), which gives an object like { temp: 21 }, and give back \"Paris: 21°\".",
 files: {"solution.cjs": "async function getWeather(city, fetchFn) {\n  // your code here\n}\n\nmodule.exports = { getWeather };\n"},
 test: "const { getWeather } = load('solution.cjs');\nconst fake = (temp, ok) => { const f = async url => { f.url = url; return { ok, json: async () => ({ temp }) }; }; return f; };\nawait check('Paris: 21°', async () => assert.strictEqual(await getWeather('Paris', fake(21, true)), 'Paris: 21°'));\nawait check('it asks the right address', async () => {\n  const f = fake(9, true);\n  await getWeather('New York', f);\n  assert.strictEqual(f.url, 'https://weather.example/api?city=New%20York');\n});\nawait check('a failed answer throws Could not get the weather', async () => {\n  let err = null;\n  try { await getWeather('Paris', fake(21, false)); } catch (e) { err = e; }\n  assert.ok(err, 'nothing was thrown');\n  assert.strictEqual(err.message, 'Could not get the weather');\n});",
 solve: {"solution.cjs": "async function getWeather(city, fetchFn) {\n  const response = await fetchFn('https://weather.example/api?city=' + encodeURIComponent(city));\n  if (!response.ok) throw new Error('Could not get the weather');\n  const data = await response.json();\n  return city + ': ' + data.temp + '°';\n}\n\nmodule.exports = { getWeather };\n"}},

{id: "build-search", skill: "build-search", kind: 'check', title: "Sort a list, then find in it fast",
 ask: "Write and export two functions in solution.cjs, no AI. sortBy(list, key) gives back a NEW list of objects sorted by that key, smallest first, and leaves the list it was given alone. binarySearch(sorted, target) finds a number in a sorted list of numbers and gives back where it is (its index), or -1 if it is not there. Binary search means: look at the middle, and throw away the half the number cannot be in, again and again. The test checks it looks at no more than about 20 items in a list of 1,000, so a plain loop or indexOf will not pass.",
 files: {"solution.cjs": "function sortBy(list, key) {\n  // your code here\n}\n\nfunction binarySearch(sorted, target) {\n  // your code here\n}\n\nmodule.exports = { sortBy, binarySearch };\n"},
 test: "const { sortBy, binarySearch } = load('solution.cjs');\ncheck('sortBy sorts by the key', () => {\n  const out = sortBy([{ n: 'b', age: 30 }, { n: 'a', age: 12 }, { n: 'c', age: 20 }], 'age');\n  assert.deepStrictEqual(out.map(p => p.n), ['a', 'c', 'b']);\n});\ncheck('sortBy leaves the original alone', () => {\n  const list = [{ age: 3 }, { age: 1 }, { age: 2 }];\n  const out = sortBy(list, 'age');\n  assert.notStrictEqual(out, list, 'it gave back the same list, not a new one');\n  assert.deepStrictEqual(list.map(p => p.age), [3, 1, 2], 'the original list changed');\n});\ncheck('binarySearch finds it', () => { assert.strictEqual(binarySearch([1, 3, 5, 7, 9], 7), 3); assert.strictEqual(binarySearch([1, 3, 5, 7, 9], 1), 0); assert.strictEqual(binarySearch([1, 3, 5, 7, 9], 9), 4); });\ncheck('binarySearch gives -1 when it is missing', () => { assert.strictEqual(binarySearch([1, 3, 5], 4), -1); assert.strictEqual(binarySearch([], 4), -1); });\ncheck('binarySearch looks at 20 items or fewer in 1,000', () => {\n  const nums = Array.from({ length: 1000 }, (_, i) => i * 2);\n  let looks = 0;\n  const watched = new Proxy(nums, { get(t, k) { if (typeof k === 'string' && /^\\d+$/.test(k)) looks++; return t[k]; } });\n  assert.strictEqual(binarySearch(watched, 1500), 750);\n  assert.ok(looks <= 20, 'it looked at ' + looks + ' items');\n});",
 solve: {"solution.cjs": "function sortBy(list, key) {\n  return [...list].sort((a, b) => (a[key] < b[key] ? -1 : a[key] > b[key] ? 1 : 0));\n}\n\nfunction binarySearch(sorted, target) {\n  let low = 0;\n  let high = sorted.length - 1;\n  while (low <= high) {\n    const mid = Math.floor((low + high) / 2);\n    const value = sorted[mid];\n    if (value === target) return mid;\n    if (value < target) low = mid + 1;\n    else high = mid - 1;\n  }\n  return -1;\n}\n\nmodule.exports = { sortBy, binarySearch };\n"}},

{id: "build-own-tests", skill: "build-own-tests", kind: 'check', title: "Tests that catch a broken copy",
 ask: "isLeapYear(year) in solution.cjs is correct. A year is a leap year if it divides by 4, except years that divide by 100, unless they also divide by 400. So 2024 and 2000 are leap years, 1900 and 2023 are not. Your job is mytest.cjs: write tests that pass on the correct function and FAIL on a broken one. Start it with  const { isLeapYear } = require(process.env.TARGET || './solution.cjs');  so the check can point it at broken copies. Use assert (const assert = require('assert')), so a wrong answer stops the file with an error. Run  node mytest.cjs  to try it.",
 files: {"solution.cjs": "function isLeapYear(year) {\n  if (year % 400 === 0) return true;\n  if (year % 100 === 0) return false;\n  return year % 4 === 0;\n}\n\nmodule.exports = { isLeapYear };\n", "mytest.cjs": "// your tests go here\n"},
 test: "const { spawnSync } = require('child_process');\nconst run = target => spawnSync(process.execPath, [path.join(here, 'mytest.cjs')], { cwd: here, encoding: 'utf8', timeout: 10000, env: Object.assign({}, process.env, target ? { TARGET: target } : {}) });\nconst src = fs.readFileSync(path.join(here, 'mytest.cjs'), 'utf8');\ncheck('mytest.cjs uses process.env.TARGET', () => assert.ok(/process\\.env\\.TARGET/.test(src), 'require(process.env.TARGET || \\'./solution.cjs\\') is missing'));\ncheck('your tests pass on the correct function', () => { const r = run(''); assert.strictEqual(r.status, 0, 'mytest.cjs failed on the correct function:\\n' + r.stdout + r.stderr); });\nconst broken = {\n  'only divides by 4': 'module.exports = { isLeapYear: y => y % 4 === 0 };',\n  'forgets 400': 'module.exports = { isLeapYear: y => y % 4 === 0 && y % 100 !== 0 };',\n  'always no': 'module.exports = { isLeapYear: y => false };'\n};\nlet n = 0;\nfor (const [name, code] of Object.entries(broken)) {\n  const f = path.join(here, 'broken' + (++n) + '.cjs');\n  fs.writeFileSync(f, code);\n  try {\n    check('your tests catch the copy that ' + name, () => assert.notStrictEqual(run(f).status, 0, 'mytest.cjs passed on a broken copy that ' + name));\n  } finally { fs.unlinkSync(f); }\n}",
 solve: {"mytest.cjs": "const assert = require('assert');\nconst { isLeapYear } = require(process.env.TARGET || './solution.cjs');\n\nassert.strictEqual(isLeapYear(2024), true, '2024 is a leap year');\nassert.strictEqual(isLeapYear(2023), false, '2023 is not');\nassert.strictEqual(isLeapYear(1900), false, '1900 divides by 100, so it is not');\nassert.strictEqual(isLeapYear(2000), true, '2000 divides by 400, so it is');\nconsole.log('all good');\n"}},

{id: "debug-typo", skill: "debug-typo", kind: 'check', title: "The total that says NaN",
 ask: "orderTotal(order) in solution.cjs should add up price times qty for every item. It gives back NaN (Not a Number, what JavaScript gives when a sum goes wrong). Find out why and fix it.",
 files: {"solution.cjs": "function orderTotal(order) {\n  let sum = 0;\n  for (const item of order.items) {\n    sum += item.prise * item.qty;\n  }\n  return sum;\n}\n\nmodule.exports = { orderTotal };\n"},
 test: "const { orderTotal } = load('solution.cjs');\ncheck('two teas and a cake is 10', () => assert.strictEqual(orderTotal({ items: [{ name: 'tea', price: 3, qty: 2 }, { name: 'cake', price: 4, qty: 1 }] }), 10));\ncheck('no items is 0', () => assert.strictEqual(orderTotal({ items: [] }), 0));",
 solve: {"solution.cjs": "function orderTotal(order) {\n  let sum = 0;\n  for (const item of order.items) {\n    sum += item.price * item.qty;\n  }\n  return sum;\n}\n\nmodule.exports = { orderTotal };\n"}},

{id: "debug-types", skill: "debug-types", kind: 'check', title: "10 plus 5 is 105",
 ask: "addUp(text) in solution.cjs gets numbers typed into a box, like \"10,5\", and should give back their sum as a number. addUp(\"10,5\") gives back \"105\". Find out why and fix it.",
 files: {"solution.cjs": "function addUp(text) {\n  const parts = text.split(',');\n  return parts.reduce((sum, part) => sum + part);\n}\n\nmodule.exports = { addUp };\n"},
 test: "const { addUp } = load('solution.cjs');\ncheck('10,5 is 15', () => assert.strictEqual(addUp('10,5'), 15));\ncheck('1,2,3 is 6', () => assert.strictEqual(addUp('1,2,3'), 6));\ncheck('spaces are fine', () => assert.strictEqual(addUp(' 4, 6 '), 10));\ncheck('one number gives that number', () => assert.strictEqual(addUp('7'), 7));",
 solve: {"solution.cjs": "function addUp(text) {\n  const parts = text.split(',');\n  return parts.reduce((sum, part) => sum + Number(part), 0);\n}\n\nmodule.exports = { addUp };\n"}},

{id: "debug-equality", skill: "debug-equality", kind: 'check', title: "Equal, but not to ===",
 ask: "Two functions in solution.cjs give wrong answers. countBad(list) should count how many entries are NaN, but it always says 0. hasPoint(list, point) should say whether a point with the same x and y is in the list, but it says false even when one is there. Find out why and fix both.",
 files: {"solution.cjs": "function countBad(list) {\n  return list.filter(value => value === NaN).length;\n}\n\nfunction hasPoint(list, point) {\n  return list.includes(point);\n}\n\nmodule.exports = { countBad, hasPoint };\n"},
 test: "const { countBad, hasPoint } = load('solution.cjs');\ncheck('two NaN in the list', () => assert.strictEqual(countBad([1, NaN, 3, NaN]), 2));\ncheck('no NaN in the list', () => assert.strictEqual(countBad([1, 2, 0]), 0));\ncheck('finds a point with the same x and y', () => assert.strictEqual(hasPoint([{ x: 5, y: 5 }, { x: 1, y: 2 }], { x: 1, y: 2 }), true));\ncheck('does not find a different point', () => assert.strictEqual(hasPoint([{ x: 1, y: 2 }], { x: 2, y: 1 }), false));",
 solve: {"solution.cjs": "function countBad(list) {\n  return list.filter(value => Number.isNaN(value)).length;\n}\n\nfunction hasPoint(list, point) {\n  return list.some(p => p.x === point.x && p.y === point.y);\n}\n\nmodule.exports = { countBad, hasPoint };\n"}},

{id: "debug-empty", skill: "debug-empty", kind: 'check', title: "Nobody sent any scores",
 ask: "average(list) and biggest(list) in solution.cjs work on a list of numbers. When the list is empty, average gives back NaN and biggest gives back undefined. For an empty list, average should give back 0 and biggest should give back null. Fix both, and keep the normal answers right.",
 files: {"solution.cjs": "function average(list) {\n  let sum = 0;\n  for (const n of list) sum += n;\n  return sum / list.length;\n}\n\nfunction biggest(list) {\n  let best = list[0];\n  for (const n of list) {\n    if (n > best) best = n;\n  }\n  return best;\n}\n\nmodule.exports = { average, biggest };\n"},
 test: "const { average, biggest } = load('solution.cjs');\ncheck('average of an empty list is 0', () => assert.strictEqual(average([]), 0));\ncheck('biggest of an empty list is null', () => assert.strictEqual(biggest([]), null));\ncheck('average still works', () => assert.strictEqual(average([2, 4, 9]), 5));\ncheck('biggest still works', () => { assert.strictEqual(biggest([3, 9, 2]), 9); assert.strictEqual(biggest([-5, -2]), -2); });",
 solve: {"solution.cjs": "function average(list) {\n  if (list.length === 0) return 0;\n  let sum = 0;\n  for (const n of list) sum += n;\n  return sum / list.length;\n}\n\nfunction biggest(list) {\n  if (list.length === 0) return null;\n  let best = list[0];\n  for (const n of list) {\n    if (n > best) best = n;\n  }\n  return best;\n}\n\nmodule.exports = { average, biggest };\n"}},

{id: "debug-float", skill: "debug-float", kind: 'check', title: "10 cents and 20 cents",
 ask: "total(prices) in solution.cjs adds up prices in dollars, and format(amount) shows one. total([0.1, 0.2]) gives back 0.30000000000000004 and the page shows \"$0.30000000000000004\". Fix it so total([0.1, 0.2]) is exactly 0.3 and format shows \"$0.30\". Hint: computers keep numbers with a decimal point slightly off, but whole numbers are exact. Work in cents.",
 files: {"solution.cjs": "function total(prices) {\n  let sum = 0;\n  for (const p of prices) sum += p;\n  return sum;\n}\n\nfunction format(amount) {\n  return '$' + amount;\n}\n\nmodule.exports = { total, format };\n"},
 test: "const { total, format } = load('solution.cjs');\ncheck('0.1 and 0.2 is exactly 0.3', () => assert.strictEqual(total([0.1, 0.2]), 0.3));\ncheck('three times 0.07 is exactly 0.21', () => assert.strictEqual(total([0.07, 0.07, 0.07]), 0.21));\ncheck('19.99 and 5.01 is 25', () => assert.strictEqual(total([19.99, 5.01]), 25));\ncheck('it shows $0.30', () => assert.strictEqual(format(total([0.1, 0.2])), '$0.30'));\ncheck('it shows $5.00', () => assert.strictEqual(format(5), '$5.00'));",
 solve: {"solution.cjs": "function total(prices) {\n  let cents = 0;\n  for (const p of prices) cents += Math.round(p * 100);\n  return cents / 100;\n}\n\nfunction format(amount) {\n  return '$' + amount.toFixed(2);\n}\n\nmodule.exports = { total, format };\n"}},

{id: "debug-scope", skill: "debug-scope", kind: 'check', title: "Every button says 4",
 ask: "makeButtons(n) in solution.cjs makes n click handlers, one for each button. Clicking a handler should say which button it is: \"Button 1\", \"Button 2\" and so on. Instead every one of them says \"Button 4\" when there are 3. Find out why and fix it so each handler keeps its own number.",
 files: {"solution.cjs": "function makeButtons(n) {\n  var handlers = [];\n  for (var i = 1; i <= n; i++) {\n    handlers.push(function () {\n      return 'Button ' + i;\n    });\n  }\n  return handlers;\n}\n\nmodule.exports = { makeButtons };\n"},
 test: "const { makeButtons } = load('solution.cjs');\ncheck('three buttons say 1, 2, 3', () => assert.deepStrictEqual(makeButtons(3).map(click => click()), ['Button 1', 'Button 2', 'Button 3']));\ncheck('the first of five says 1', () => assert.strictEqual(makeButtons(5)[0](), 'Button 1'));",
 solve: {"solution.cjs": "function makeButtons(n) {\n  const handlers = [];\n  for (let i = 1; i <= n; i++) {\n    handlers.push(function () {\n      return 'Button ' + i;\n    });\n  }\n  return handlers;\n}\n\nmodule.exports = { makeButtons };\n"}},

{id: "debug-regression", skill: "debug-regression", kind: 'check', title: "Someone tidied it up",
 ask: "before.cjs is slugify(title) as it was, and it worked: \"  Tea & Cake!  \" became \"tea-cake\". Someone tidied it into after.cjs, and now some titles come out wrong. Find what changed. In a terminal in this folder, run  git diff --no-index before.cjs after.cjs  to see the two side by side (lines starting with a minus sign were taken out, lines starting with a plus sign were put in). Then fix after.cjs so it does everything before.cjs did. The test runs after.cjs.",
 files: {"before.cjs": "function slugify(title) {\n  let s = title.toLowerCase();\n  s = s.replace(/[^a-z0-9]+/g, '-');\n  s = s.replace(/^-+|-+$/g, '');\n  return s;\n}\n\nmodule.exports = { slugify };\n", "after.cjs": "// tidied up: one line is easier to read\nconst slugify = title => title.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-');\n\nmodule.exports = { slugify };\n"},
 test: "const { slugify } = load('after.cjs');\ncheck('Hello World', () => assert.strictEqual(slugify('Hello World'), 'hello-world'));\ncheck('Top 10: Best', () => assert.strictEqual(slugify('Top 10: Best'), 'top-10-best'));\ncheck('no dash at the end', () => assert.strictEqual(slugify('  Tea & Cake!  '), 'tea-cake'));\ncheck('no dash at the start', () => assert.strictEqual(slugify('#1 Pick'), '1-pick'));",
 solve: {"after.cjs": "// tidied up, and still strips the dashes at the ends\nconst slugify = title => title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');\n\nmodule.exports = { slugify };\n"}}
);
