/* Step by step for Part 2 Tweaker and Part 3 Writer */
window.OPESteps = window.OPESteps || {};
Object.assign(window.OPESteps, {
  'tweak-value': { all: [
    "Look at the editor in this card. The tab at the top says solution.cjs, and the big box under it shows that file.",
    "Find line 1, which says `const FREE_SHIPPING_OVER = 100;`. `const` gives a value a name. Here the name is FREE_SHIPPING_OVER and the value is 100.",
    "Double click the number 100 on that line so it is selected.",
    "Type `50`. Line 1 now says `const FREE_SHIPPING_OVER = 50;`.",
    "Leave every other line as it is. Line 4 already uses FREE_SHIPPING_OVER, so it picks up the new number by itself.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-condition': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "Find line 2, which says `  return day === 'Sunday';`. `===` asks \"is this exactly the same?\", so right now only 'Sunday' gives true.",
    "Click just after `'Sunday'`, between the closing quote mark and the semicolon `;`.",
    "Type ` || day === 'Saturday'` with one space at the start. `||` means \"or\".",
    "Line 2 now says `  return day === 'Sunday' || day === 'Saturday';`. Make sure the `;` is still at the very end.",
    "Leave the other lines as they are.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-text': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "Find line 2, which says `  return 'Hello, ' + name;`. The words inside quote marks are the text the person sees. `+` joins pieces of text together, and name is whatever name was given.",
    "Double click the word `Hello` inside the quotes so only that word is selected.",
    "Type `Welcome back`. Line 2 now says `  return 'Welcome back, ' + name;`. Keep the comma and the space before the closing quote.",
    "Click at the end of line 2, just before the `;`.",
    "Type ` + '!'` with one space at the start. This joins an exclamation mark onto the end.",
    "Line 2 now says `  return 'Welcome back, ' + name + '!';`.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-data': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "MENU is a list. A list holds things in order between `[` and `]`, with a comma between each thing. Each thing here is an object: named parts between `{` and `}`, here a name and a price.",
    "Find line 3, which says `  { name: 'Tea', price: 2 }`. It has no comma at the end because it is the last thing in the list.",
    "Click at the very end of line 3, just after the `}`.",
    "Type a comma `,`. Every thing in a list except the last one needs a comma after it.",
    "Press Return to start a new line, then press Tab once. Tab puts in two spaces so it lines up.",
    "Type `{ name: 'Juice', price: 4 }` with no comma after it, because Juice is now the last thing.",
    "Lines 2 to 4 now say `  { name: 'Coffee', price: 3 },` then `  { name: 'Tea', price: 2 },` then `  { name: 'Juice', price: 4 }`. The line after them is still `];`, which closes the list.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-loop': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "Find line 3, which says `  for (let i = 10; i > 0; i--) {`. A loop repeats the lines between its `{` and `}`. The brackets hold three parts split by semicolons: where i starts, the rule for going round again, and what happens after each round (`i--` takes 1 away).",
    "On line 3, double click the number 10 so it is selected, and type `5`. Now i starts at 5.",
    "Still on line 3, click just after the `>` sign in `i > 0`.",
    "Type `=` so it says `i >= 0`. `>=` means \"bigger than or the same as\", so the loop also runs when i is 0.",
    "Line 3 now says `  for (let i = 5; i >= 0; i--) {`. Leave `i--` and the other lines as they are.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'door-2': { all: [
    "This is the Part 2 door test: four small changes in solution.cjs, each like one you have already done. Do them one at a time.",
    "Change 1. Find line 1, `const OPENS = 9;`. Double click the 9 and type `8`. Line 1 now says `const OPENS = 8;`.",
    "Change 2. Find line 6, `  const workday = day !== 'Saturday' && day !== 'Sunday';`. `!==` means \"is not\" and `&&` means \"and\", so right now a workday is not Saturday and not Sunday.",
    "On line 6, click just before the first `day` (the one right after `= `). Hold Shift and click just before the second `day`. This selects `day !== 'Saturday' && `. Press Delete.",
    "Line 6 now says `  const workday = day !== 'Sunday';`. Now only Sunday is shut.",
    "Change 3. Find line 11, `  return isOpen(day, hour) ? 'Open' : 'Closed';`. The `?` picks the text before the `:` when the shop is open, and the text after it when it is shut.",
    "Double click the word `Open` inside the quotes (the one in `'Open'`, not the one in isOpen) and type `Come in, we are open`. Line 11 now says `  return isOpen(day, hour) ? 'Come in, we are open' : 'Closed';`.",
    "Change 4. Find line 3, `const ITEMS = [{ name: 'Muffin', price: 3 }];`. Click between the `}` and the `]`.",
    "Type `, { name: 'Bagel', price: 2 }`. Line 3 now says `const ITEMS = [{ name: 'Muffin', price: 3 }, { name: 'Bagel', price: 2 }];`.",
    "Leave CLOSES and everything else as it is.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-style': { all: [
    "Look at the editor in this card. The tab says style.css and the big box shows the file.",
    "A CSS rule is a name like `.button`, then `{`, then lines of `property: value;`, then `}`. The .button rule is lines 6 to 11.",
    "Find line 7, which says `  background: #3B82F6;`. Double click `3B82F6` (the letters and numbers after the #) so it is selected.",
    "Type `22C55E`. Line 7 now says `  background: #22C55E;`.",
    "Find line 8, which says `  color: #111827;`. Drag from the `#` to the `7` so `#111827` is selected. Do not select the `;`.",
    "Type `white`. Line 8 now says `  color: white;`.",
    "Leave line 3, `  color: #1F2937;`, alone. It belongs to the body rule, not the button. Leave the padding and border-radius lines alone too.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-html': { all: [
    "Look at the editor in this card. The tab says index.html and the big box shows the file.",
    "HTML is made of tags. `<h1>` opens a big heading, `</h1>` closes it, and the words between them are what the page shows.",
    "Find line 9, which says `    <h1>Welcome</h1>`. Double click the word Welcome so it is selected.",
    "Type `Fresh cuts, booked in a minute.` including the full stop. Line 9 now says `    <h1>Fresh cuts, booked in a minute.</h1>`.",
    "Click at the very end of line 9, just after `</h1>`. Press Return to start a new line.",
    "Press Tab twice so there are four spaces and the new line lines up with the h1.",
    "Type `<a href=\"/book\">Book now</a>`. `<a>` is a link, and href says where it goes.",
    "The next line should still be `  </header>`, so the link sits inside the header. Leave the title, the stylesheet line and the paragraph as they are.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-config': { all: [
    "Look at the editor in this card. The tab says settings.json and the big box shows the file.",
    "Each line inside is a pair: a key in double quotes, a colon, then its value. true and false have no quotes. Text has double quotes.",
    "Find line 3, which says `  \"darkMode\": false,`. Double click the word false and type `true`. Line 3 now says `  \"darkMode\": true,` with no quotes around true.",
    "Find line 4, which says `  \"currency\": \"USD\",`. Double click USD (inside the quotes) and type `EUR`. Line 4 now says `  \"currency\": \"EUR\",`. Keep both quote marks and the comma.",
    "Do not touch any other line. One missing comma or quote mark breaks the whole file, and the test will say it is not valid JSON.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-field': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "The word nm is in six places: once on line 1, twice on line 2, once on line 6 and twice on line 10. You will change each one to name.",
    "Line 1 says `function makePerson(nm, age) {`. Double click nm and type `name`. It now says `function makePerson(name, age) {`.",
    "Line 2 says `  return { nm: nm, age: age };`. Double click the first nm (before the colon) and type `name`. Then double click the second nm (after the colon) and type `name`. It now says `  return { name: name, age: age };`.",
    "Line 6 says `  return person.nm + ' is ' + person.age;`. Double click the nm after `person.` and type `name`. It now says `  return person.name + ' is ' + person.age;`.",
    "Line 10 says `  return people.slice().sort((a, b) => a.nm.localeCompare(b.nm));`. Double click the nm in `a.nm` and type `name`. Then double click the nm in `b.nm` and type `name`.",
    "Line 10 now says `  return people.slice().sort((a, b) => a.name.localeCompare(b.name));`.",
    "Read the whole file once more from top to bottom. nm must not appear anywhere.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-default': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "Find line 1, which says `function greet(name) {`. The word inside the brackets is the input the function is given.",
    "Click just after the word name, before the `)`.",
    "Type ` = 'friend'` with one space at the start. This means: if no name is given, use 'friend'.",
    "Line 1 now says `function greet(name = 'friend') {`. Leave line 2 as it is.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-order': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "Find line 2, which says `  return items.slice().sort((a, b) => a.price - b.price);`. sort compares two things at a time, a and b. `a.price - b.price` puts the cheaper one first. Swapping a and b in that sum puts the dearer one first.",
    "Double click the `a` in `a.price` (the one just after `=>`) and type `b`.",
    "Now double click the `b` in the last `b.price` (just before the `)`) and type `a`.",
    "Line 2 now says `  return items.slice().sort((a, b) => b.price - a.price);`. Do not change `(a, b)` and leave `.slice()` in, it makes the copy that gets sorted.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'tweak-remove': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file. You will take out four pieces.",
    "Piece 1. Click at the very start of line 1, `const DISCOUNT = 0.1;`. Hold Shift and click at the very start of line 7, `function subtotal(items) {`. This selects lines 1 to 6: the DISCOUNT value, the discount function and the empty line after it. Press Delete.",
    "The file now starts with `function subtotal(items) {`.",
    "Piece 2. Find the line `  return sub - discount(sub);` inside total (about line 7 now). Click just after `sub`, before the space and the minus sign. Hold Shift and click just before the `;`. This selects ` - discount(sub)`. Press Delete.",
    "That line now says `  return sub;`, so total gives the full price.",
    "Piece 3. Find the last line, `module.exports = { subtotal, total, discount };`. Select `, discount` (the comma, the space and the word) and press Delete.",
    "The last line now says `module.exports = { subtotal, total };`.",
    "Read the whole file once more. The word discount must not be anywhere, in small or capital letters.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-function': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "A function is a named set of steps. Its inputs go in the brackets, here price and quantity, and its steps go between `{` and `}`.",
    "Line 2 says `  // your code here`. `//` starts a comment, a note the computer ignores. You will replace it.",
    "Drag from the first `/` to the end of `here` so `// your code here` is selected. Keep the two spaces before it.",
    "Type `return price * quantity;`. `return` hands a value back to whoever used the function. `*` means times. The `;` ends the line.",
    "Line 2 now says `  return price * quantity;` and line 3 is still `}`.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-if': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "`if (test) return X;` checks the test. If it is true, the function gives back X and stops right there. So check the highest grade first.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `if (score >= 90) return 'A';`. `>=` means \"the same or more\".",
    "Press Return, press Tab once for two spaces, and type `if (score >= 80) return 'B';`. You only get here if the score was under 90.",
    "Press Return, press Tab once, and type `if (score >= 70) return 'C';`.",
    "Press Return, press Tab once, and type `return 'F';`. It has no if, because anything left is an F.",
    "The function now reads `function grade(score) {`, then your four lines, then `}`.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-loop': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `let sum = 0;`. `let` makes a named value that can change later. sum is the running total, and it starts at 0.",
    "Press Return, press Tab once, and type `for (let i = 1; i <= n; i++) {`. A loop repeats the lines between `{` and `}`. i starts at 1, the loop keeps going while i is n or less, and `i++` adds 1 after each round.",
    "Press Return, press Tab twice for four spaces, and type `sum = sum + i;`. Each round adds this round's number to the running total.",
    "Press Return, press Tab once, and type `}`. This closes the loop.",
    "Press Return, press Tab once, and type `return sum;`. When the loop is done, give back the total.",
    "The whole function is now `function sumTo(n) {`, `  let sum = 0;`, `  for (let i = 1; i <= n; i++) {`, `    sum = sum + i;`, `  }`, `  return sum;`, `}`.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-data': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "items is a list: things in order between `[` and `]`. Each thing is an object, named parts between `{` and `}`, so `item.price` reads the price and `item.name` reads the name.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `const names = [];`. This makes an empty list that will collect the names.",
    "Press Return, press Tab once, and type `for (const item of items) {`. This loop goes through the list one thing at a time, and calls the current thing item.",
    "Press Return, press Tab twice, and type `if (item.price <= max) {`. `<=` means \"the same or less\".",
    "Press Return, press Tab three times, and type `names.push(item.name);`. push adds the name to the end of the names list.",
    "Press Return, press Tab twice, and type `}` to close the if.",
    "Press Return, press Tab once, and type `}` to close the loop.",
    "Press Return, press Tab once, and type `return names;`. This gives back the list of names.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-errors': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "`throw new Error('...')` stops the function at once and reports a problem with that message.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `const n = Number(text);`. Number turns text like \"42\" into the number 42. Text that is not a number becomes NaN, which means \"not a number\".",
    "Press Return, press Tab once, and type `if (!Number.isInteger(n)) {`. Number.isInteger is true only for whole numbers, and `!` means \"not\".",
    "Press Return, press Tab twice, and type `throw new Error('Not a number');`.",
    "Press Return, press Tab once, and type `}` to close that if.",
    "Press Return, press Tab once, and type `if (n > 150) {`.",
    "Press Return, press Tab twice, and type `throw new Error('Too old');`.",
    "Press Return, press Tab once, and type `}`.",
    "Press Return, press Tab once, and type `return n;`. If you get here the age is fine, so give it back.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'door-3': { all: [
    "This is the Part 3 door test. You write receipt from small pieces. Each item looks like `{ name: 'Tea', price: 2, qty: 3 }`.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `if (items.length === 0) {`. `.length` is how many things are in the list.",
    "Press Return, press Tab twice, and type `throw new Error('Nothing to pay for');`. throw stops the function and reports the problem.",
    "Press Return, press Tab once, and type `}`.",
    "Press Return, press Tab once, and type `let count = 0;`. Then on new lines, each with Tab once, type `let total = 0;` and `let dearest = items[0];`. `items[0]` is the first thing in the list, because lists count from 0.",
    "Press Return, press Tab once, and type `for (const item of items) {`. This loop goes through the list one item at a time.",
    "Press Return, press Tab twice, and type `if (item.price < 0) {`.",
    "Press Return, press Tab three times, and type `throw new Error('Bad price');`.",
    "Press Return, press Tab twice, and type `}`.",
    "Press Return, press Tab twice, and type `count = count + item.qty;`. This adds up how many things.",
    "Press Return, press Tab twice, and type `total = total + item.price * item.qty;`. This adds price times how many to the money.",
    "Press Return, press Tab twice, and type `if (item.price > dearest.price) {`. Then press Return, Tab three times, and type `dearest = item;`. Then press Return, Tab twice, and type `}`.",
    "Press Return, press Tab once, and type `}` to close the loop.",
    "Press Return, press Tab once, and type `return { count: count, total: total, dearest: dearest.name };`. This gives back an object with the three answers, and dearest is just the name.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-strings': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `const cleanFirst = first.trim();`. trim cuts the spaces off the start and the end.",
    "Press Return, press Tab once, and type `const cleanLast = last.trim();`.",
    "Press Return, press Tab once, and type `return cleanLast + ', ' + cleanFirst;`. `return` gives the text back. `+` joins the pieces: the last name, a comma and a space, then the first name.",
    "The function now has three lines between `function formatName(first, last) {` and `}`.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-math': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `const each = Math.floor(totalCents / people);`. `/` divides, and Math.floor rounds down, so 1000 for 3 gives 333.",
    "Press Return, press Tab once, and type `const extra = totalCents % people;`. `%` gives what is left over, so 1000 for 3 leaves 1 cent.",
    "Press Return, press Tab once, and type `const out = [];`. This is an empty list, `[]`, that will hold one amount for each person.",
    "Press Return, press Tab once, and type `for (let i = 0; i < people; i++) {`. This loop runs once for each person. i counts 0, 1, 2 and so on.",
    "Press Return, press Tab twice, and type `if (i < extra) {`. The first people, as many as there are extra cents, pay one more.",
    "Press Return, press Tab three times, and type `out.push(each + 1);`. push adds an amount to the end of the list.",
    "Press Return, press Tab twice, and type `} else {`. else is what happens when the if is not true.",
    "Press Return, press Tab three times, and type `out.push(each);`.",
    "Press Return, press Tab twice, and type `}` to close the if. Press Return, press Tab once, and type `}` to close the loop.",
    "Press Return, press Tab once, and type `return out;`. This gives back the list.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-objects': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "An object is a set of named parts, called fields, between `{` and `}`. Each field is written `name: value`, with a comma between fields.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `return {`. `return` hands back what follows, and `{` starts the object.",
    "Press Return, press Tab twice, and type `name: name,`. The field called name gets the name that was given.",
    "Press Return, press Tab twice, and type `service: service,`.",
    "Press Return, press Tab twice, and type `price: price,`.",
    "Press Return, press Tab twice, and type `status: 'held',`. This one is always the text 'held'.",
    "Press Return, press Tab twice, and type `createdAt: new Date()`. `new Date()` is the time right now. No comma here, because it is the last field.",
    "Press Return, press Tab once, and type `};` to close the object.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-map-filter': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "orders is a list. `.filter(...)` keeps only the things for which a test is true. `.map(...)` turns each thing into something else. Inside them you write a tiny function like `order => order.id`, which means \"given an order, give back its id\".",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `const wanted = orders.filter(order => order.paid && order.total > 20);`. This keeps orders that are paid and (`&&`) over 20. `>` means over, so exactly 20 is left out.",
    "Press Return, press Tab once, and type `return wanted.map(order => order.id);`. This turns each kept order into its id and gives back that list.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-find': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows three functions, each with a `// your code here` line.",
    "In findUser, on line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `const user = users.find(u => u.email === email);`. `.find` goes through the list and gives back the first user whose email matches. If none match it gives undefined, which means nothing.",
    "Press Return, press Tab once, and type `if (user === undefined) {`.",
    "Press Return, press Tab twice, and type `return null;`. The task wants null, not undefined, when there is no such user.",
    "Press Return, press Tab once, and type `}`. Press Return, press Tab once, and type `return user;`.",
    "Now go down to allAdults and select its `// your code here`.",
    "Type `return users.every(u => u.age >= 18);`. `.every` is true only if the test is true for every user.",
    "Now go down to anyAdmin and select its `// your code here`.",
    "Type `return users.some(u => u.role === 'admin');`. `.some` is true if the test is true for at least one user.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-dates': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows the file.",
    "On line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `const partsA = a.split('-');`. split cuts the text at each `-`, so \"2026-09-01\" becomes the list ['2026', '09', '01'].",
    "Press Return, press Tab once, and type `const partsB = b.split('-');`.",
    "Press Return, press Tab once, and type `const timeA = Date.UTC(Number(partsA[0]), Number(partsA[1]) - 1, Number(partsA[2]));`. `partsA[0]` is the first piece, because lists count from 0. Number turns text into a number. The month has 1 taken off because Date.UTC counts months from 0.",
    "Press Return, press Tab once, and type `const timeB = Date.UTC(Number(partsB[0]), Number(partsB[1]) - 1, Number(partsB[2]));`.",
    "Press Return, press Tab once, and type `const days = Math.abs(timeB - timeA) / 86400000;`. Math.abs drops a minus sign, so the order of the dates does not matter. 86400000 is one day in milliseconds.",
    "Press Return, press Tab once, and type `return Math.round(days);`. This rounds to a whole number of days and gives it back.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] },
  'write-validation': { all: [
    "Look at the editor in this card. The tab says solution.cjs and the big box shows two functions, each with a `// your code here` line.",
    "A regular expression is a pattern between slashes. `^` means the start, `$` means the end, `+` means one or more, `[^\\s@]` means any one character that is not a space and not an @, and `\\.` means a real dot. `.test(text)` gives true if the text fits the pattern, false if not.",
    "In isEmail, on line 2, select `// your code here` (drag from the first `/` to the end of `here`).",
    "Type `return /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/.test(text);`. It reads: some characters, one @, more characters, a dot, more characters, and no spaces anywhere.",
    "Now go down to isPhone and select its `// your code here`.",
    "Type `if (!/^\\+?[\\d\\s-]+$/.test(text)) {`. `\\+?` allows one plus sign at the start only, and `[\\d\\s-]+` allows digits, spaces and dashes. `!` means \"not\", so this catches text that does not fit.",
    "Press Return, press Tab twice, and type `return false;`. Press Return, press Tab once, and type `}`.",
    "Press Return, press Tab once, and type `const digits = text.replace(/\\D/g, '');`. `\\D` is anything that is not a digit and `g` means everywhere, so this takes out the spaces, dashes and plus and keeps only the digits.",
    "Press Return, press Tab once, and type `return digits.length >= 10 && digits.length <= 15;`. `.length` is how many digits are left, and `&&` means both must be true.",
    "Press Save. On a Mac you can press Command S instead, on Windows Control S.",
    "Press Check my work. It saves, runs the test and shows a PASS or FAIL line for each thing it checks.",
    "If a line says FAIL, read the words after FAIL. They say what is still wrong. Fix that one thing, then press Check my work again until every line says PASS."
  ] }
});
